name: specimen_one
description: "Offline-fähiges Leistungsverzeichnis für medizinische Einrichtungen"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Komponenten
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9  # Bereits vorhanden, wird für SVG-Icons verwendet
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  
  # Zustandsverwaltung
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Lokale Datenbank und Offline-Speicherung
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Netzwerk und Synchronisation
  http: ^1.1.2
  connectivity_plus: ^5.0.2
  
  # Hilfspakete
  intl: ^0.19.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  uuid: ^4.2.2
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code-Generierung
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # App-Icons
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets für die App
  assets:
    - assets/data/
    - assets/images/
    - assets/images/icons/

# Konfiguration für App-Icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/icon_1024x1024.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icons/icon-1024x1024-b.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: false

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

